---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/generators.external-secrets.io/password_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: ${APP}
spec:
  allowRepeat: true
  digits: 5
  length: 42
  noUpper: false
  symbolCharacters: "-_$@"
  symbols: 5