apiVersion: v1
kind: Secret
metadata:
  name: external-dns-aws
  namespace: network
stringData:
  access_key: ENC[AES256_GCM,data:op/U7h2nUmTCFNl5Yuz3aHX29n0=,iv:94xq91q+kB8TNDKWXZYuw69OSzQyc1y+BO7KN4G3Qc8=,tag:qg0tMEvRsL9rr/hbHmaoPg==,type:str]
  secret_key: ENC[AES256_GCM,data:nN4Jk77SF4Zy0fOSu8CKNhAjRhW+tf0jNAZZMCk48juQSXuN53C8Rw==,iv:7Zt/udkyxAl9F74XTS/1T2A2B4GZ9f0ukStO84LKFtU=,tag:JJxYOzljdBbdC/3l8+Hw3A==,type:str]
sops:
  age:
    - recipient: age1uz35yjytjahj2nydce709njxklnd89ahchtn7xcpvcje3z7zeftqfqsqhu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxd2RKcXlzUmwxS0doTVM4
        MktqVkRsTENQZm1QSDJtcmpmVGMycUVwa0VNCkZhaytCR3dZK09Xclk3djlDN2JP
        OW10VG9wOXIyelUwTUpUTFhhTHlCZFUKLS0tIGU5amJTaFRKSjJXd2IzZndSWWUr
        bzc0aVhzemUxSnhQUkxwR2hocTdNVm8K6z5nTOsGghHMd+ePx5MpggZGBWE56uY3
        xPOmQAF+XzXdw8u7qoMVNa0K7IvXp6ZuF2kx3hV7rswX/l4TuISuvw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-01T13:15:30Z"
  mac: ENC[AES256_GCM,data:ZawL8jTvCxmjREckMIkwc4XARlM3nC/wJ+ckQIAsuFfTkkj3pve6wNc3MCqshXXfR97wTFdzhmUzKhpOnUtrdX+qkVzxYXaBLJ1W5sS8GSwvPHrA4VPtYpBJq8gyqA5sQvVvZN5xoQaL+di0gKWVBwpKBYdVNnYgjn6ovLtycNc=,iv:iW+LkTScF8nMvbXbWgHyJBGZVNfU3WKDF8OUeGkMvj0=,tag:J3kS1Sxal/2siyMS9F9MIQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
