---
# yaml-language-server: $schema=https://raw.githubusercontent.com/kubernetes-sigs/external-dns/refs/heads/master/charts/external-dns/values.schema.json
domainFilters:
  - ${CLUSTER_DOMAIN}
env:
  - name: &name AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        key: *name
        name: &secret external-dns-aws
  - name: &name AWS_REGION
    valueFrom:
      secretKeyRef:
        key: *name
        name: *secret
  - name: &name AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        key: *name
        name: *secret
policy: sync
provider: aws
serviceMonitor:
  enabled: true
sources:
  - gateway-httproute
  - service
txtOwnerId: default
txtPrefix: k8s.