---
# Area
area/bootstrap:
  - changed-files:
    - any-glob-to-any-file:
        - "bootstrap/**/*"
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "README.md"
area/github:
  - changed-files:
    - any-glob-to-any-file:
        - ".github/**/*"
area/kubernetes:
  - changed-files:
    - any-glob-to-any-file:
        - "kubernetes/**/*"
area/terraform:
  - changed-files:
    - any-glob-to-any-file:
        - "terraform/**/*"
# Cluster
cluster/home:
  - changed-files:
    - any-glob-to-any-file:
        - "kubernetes/**/home/**/*"
cluster/oci:
  - changed-files:
    - any-glob-to-any-file:
        - "kubernetes/**/oci/**/*"