---
# Areas
- name: area/bootstrap
  color: "0e8a16"
- name: area/docs
  color: "0e8a16"
- name: area/github
  color: "0e8a16"
- name: area/kubernetes
  color: "0e8a16"
- name: area/terraform
  color: "0e8a16"
  # Clusters
- name: cluster/home
  color: "ffc300"
- name: cluster/oci
  color: "ffc300"
# Renovate Types
- name: renovate/container
  color: "027fa0"
- name: renovate/github-action
  color: "027fa0"
- name: renovate/github-release
  color: "027fa0"
- name: renovate/helm
  color: "027fa0"
- name: renovate/terraform
  color: "027fa0"
# Semantic Types
- name: type/digest
  color: "ffeC19"
- name: type/major
  color: "f6412d"
- name: type/minor
  color: "ff9800"
- name: type/patch
  color: "ffeC19"