[env]
KUBECONFIG = "{{config_root}}/kubeconfig"

[tools]
"aqua:cilium/cilium-cli" = "0.18.3"
"aqua:helm/helm" = "3.17.3"
"aqua:helmfile/helmfile" = "1.0.0"
"aqua:kubernetes/kubectl" = "1.33.0"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
