---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kustomize-mutating-webhook
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kustomize-mutating-webhook
      sourceRef:
        kind: HelmRepository
        name: fluxcd-kustomize-mutating-webhook
        namespace: flux-system
      version: 0.7.0
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  interval: 1h
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: kustomize-mutating-webhook-values