---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gateway-helm
  namespace: flux-system
spec:
  interval: 1h
  ref:
    tag: 1.4.1
  url: oci://docker.io/envoyproxy/gateway-helm