---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/master/storageclass.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfspv
allowVolumeExpansion: true
parameters:
  compression: lz4
  dedup: off
  fstype: zfs
  poolname: tank/k8s/volumes
  recordsize: 128k
  shared: yes
  thinprovision: yes
provisioner: zfs.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer