---
controller:
  admissionWebhooks:
    objectSelector:
      matchExpressions:
        - key: ingress-class
          operator: In
          values:
            - internal
  ingressClassResource:
    name: internal
    default: true
    controllerValue: k8s.io/internal
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  service:
    annotations:
      tailscale.com/hostname: "internal"
    loadBalancerClass: tailscale
fullnameOverride: ingress-nginx-internal