---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: cert-manager-values
    files:
      - values.yaml=./values.yaml
configurations:
  - kustomizeconfig.yaml
resources:
  - helmrelease.yaml
  - letsencrypt.yaml
  - secret.sops.yaml
  - selfsigned.yaml