---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/flux-system
  - ../base/flux-system/addons/ks.yaml
  - ../base/kube-system
  # - ../base/kube-system/cilium/ks.yaml
  - ./kube-system/cilium/ks.yaml
  - ../base/kube-system/reflector/ks.yaml
  - ../base/kube-system/talos-cloud-controller-manager/ks.yaml
  - ../base/network
  # - ../base/network/envoy-gateway/ks.yaml
  - ./network/envoy-gateway/ks.yaml
  - ../base/security
  - ../base/security/cert-manager/ks.yaml