---
domainFilters:
  - themacdonald.house
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        key: cloudflare_api_token
        name: external-dns-secret
extraArgs:
  - --cloudflare-dns-records-per-page=1000
  - --cloudflare-proxied
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --gateway-name=external
policy: sync
provider: cloudflare
serviceMonitor:
  enabled: true
sources:
  - crd
  - gateway-httproute
txtOwnerId: default
txtPrefix: k8s.