---
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        isDefault: true
        url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090/