---
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - disableDeletion: false
        editable: true
        folder: ''
        name: 'default'
        options:
          path: /var/lib/grafana/dashboards/default
        orgId: 1
        type: file
dashboards:
  default:
    cilium-dashboard:
      datasource: Prometheus
      url: https://raw.githubusercontent.com/cilium/cilium/refs/tags/v1.17.0/install/kubernetes/cilium/files/cilium-agent/dashboards/cilium-dashboard.json
    cilium-operator-dashboard:
      datasource: Prometheus
      url: https://raw.githubusercontent.com/cilium/cilium/refs/tags/v1.17.0/install/kubernetes/cilium/files/cilium-operator/dashboards/cilium-operator-dashboard.json
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - access: proxy
        isDefault: true
        name: Prometheus
        type: prometheus
        url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090/
ingress:
  enabled: true
  hosts:
    - grafana.themacdonald.house
  ingressClassName: internal
sidecar:
  dashboards:
    enabled: true
    folderAnnotation: grafana_folder
    provider:
      foldersFromFilesStructure: true