---
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - disableDeletion: false
        editable: true
        folder: ''
        name: 'default'
        options:
          path: /var/lib/grafana/dashboards/default
        orgId: 1
        type: file
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - access: proxy
        isDefault: true
        name: Prometheus
        type: prometheus
        url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090/
sidecar:
  dashboards:
    enabled: true
    folderAnnotation: grafana_folder
    provider:
      foldersFromFilesStructure: true