---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: cilium-values
    namespace: kube-system
    files:
      - values.yaml=./values.yaml
configurations:
  - kustomizeconfig.yaml
namespace: kube-system
resources:
  - gateway.yaml
  - helmrelease.yaml
  - loadbalancer.yaml
  - redirect.yaml