---
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
dashboards:
  enabled: true
endpointRoutes:
  enabled: true
envoy:
  prometheus:
    serviceMonitor:
      enabled: true
  rollOutPods: true
gatewayAPI:
  enableAlpn: true
  enabled: true
hubble:
  enabled: true
  metrics:
    dashboards:
      enabled: true
    enabled:
      - dns:query
      - drop
      - flow
      - http
      - icmp
      - port-distribution
      - tcp
    serviceMonitor:
      enabled: true
ipam:
  mode: kubernetes
ipv4NativeRoutingCIDR: 10.42.0.0/24
k8sServiceHost: 127.0.0.1
k8sServicePort: 6443
kubeProxyReplacement: true
l2announcements:
  enabled: true
operator:
  dashboards:
    enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  replicas: 1
  rollOutPods: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
routingMode: native
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - IPC_LOCK
      - KILL
      - NET_ADMIN
      - NET_RAW
      - SETGID
      - SETUID
      - SYS_ADMIN
      - SYS_RESOURCE
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE