---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden
spec:
  provider:
    bitwardensecretsmanager:
      auth:
        secretRef:
          credentials:
            key: access-token
            name: bitwarden
            namespace: security
      bitwardenServerSDKURL: https://bitwarden-sdk-server.security.svc.cluster.local:9998
      caProvider:
        key: ca.crt
        name: bitwarden-tls-certs
        namespace: security
        type: Secret
      organizationID: ${CLUSTER_BITWARDEN_ORGANIZATION_ID}
      projectID: ${CLUSTER_BITWARDEN_PROJECT_ID}