---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitwarden
spec:
  data:
    - remoteRef:
        key: bitwarden-access-token
      secretKey: key
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: bitwarden
    template:
      data:
        access-token: '{{ .key }}'