apiVersion: v1
kind: Secret
metadata:
  name: sops-age
  namespace: flux-system
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
data:
  age.agekey: ENC[AES256_GCM,data:OlGhQ3UHjk0xurNeRstt+tNpWdje9pDklShXnBuOwwYBjKEVMIsE7KvC4PrW6OQpAAFORDojQrz9xIBslWTCw79GyARohSCpy8TWjxzmeqXTUHxE5B8Vys/PDofrKZw8Nkq9AVe8s+n39AqSQsqMky9Vi3IalVO0oZr05hyV8sw0dGe+KJXq3ZO+U/G8IR3xIdlA3EUdWhJflflBHEoSxS+f+UNqU+gLbZH/Em6KaKdM9EF0dLe3IHqVH4kgMvf1bT/irpi/mBL3je0ftCoWLg3/RdU144kf/F0mYthgf78aE+UdKaVrnW7r4caZJ2oK/SonHsw/+GeZDBvT,iv:5DcD+EYZQ52nYpvZzqHyn7Ubkl6PhSxiUcWRNVeFG+I=,tag:Cao3DPgfbB2TTxCB7PlzmA==,type:str]
type: Opaque
sops:
  age:
    - recipient: age1uz35yjytjahj2nydce709njxklnd89ahchtn7xcpvcje3z7zeftqfqsqhu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MmNOdzdrbTJ4d0I0anRr
        UnF1VGNkK3RaM0xQN1ArM00xemtFek5QNzBjCjc0TGliSlJWdTMvZ2l1VnE2UVE2
        a1c2MnpXOHZPVXk2Qm9jMTIxSDlGRlUKLS0tIDNiVkdscHVJQm4ydHdldHNXTVV1
        V3Q1TkN6TW5xaldWdWw4bThoa3lWOVUKdmIdS/DUZ88r/AoHfw0crfKWwJPLYTl4
        FKdrmu3SUcTB12Ul9Yc7jdZvLkLUUO6liNShFh3weSCGzWwriVnBTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-25T04:32:45Z"
  mac: ENC[AES256_GCM,data:aMe6YfMC6sZRWKbcfuH8iMF+NJMXiaQHvyF+pVyH02HJgMhQRQWu3zs8rpVb1cGlQiKfNRgqt/u02Ny/iihEFhKQ/9LgevV3Nvt3ZMrFq/FH45xs1Fh0VlbliDalImcOv4LXOmwgNQjdNw05rNpXM7Hegx4FYcBhJwfq6CdbXOA=,iv:Aa/TOBKNtuMT4nJ+7pT2yWjBSQrM/F3lw4pvoCGbwQg=,tag:S2E+pnyVYAomdt0hB0wXpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
