---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/gateway_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  annotations:
    external-dns.alpha.kubernetes.io/target: &hostname internal.themacdonald.house
spec:
  addresses:
    - type: IPAddress
      value: 192.168.0.180
  gatewayClassName: cilium
  infrastructure:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: *hostname
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      hostname: "*.themacdonald.house"
      name: http
      port: 80
      protocol: HTTP
    # - allowedRoutes:
    #     namespaces:
    #       from: All
    #   hostname: "*.themacdonald.house"
    #   name: https
    #   port: 443
    #   protocol: HTTPS
    #   tls:
    #     certificateRefs:
    #       - kind: Secret
    #         name: themacdonald-house-tls