---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 10m
  patches:
    # Add postBuild substitutions to child Kustomizations
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          postBuild:
            substituteFrom:
              - kind: Secret
                name: cluster-secrets
                optional: false
      target:
        group: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
  path: ./kubernetes/apps/oci
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
        optional: true
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: true