---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: fluxcd-kustomize-mutating-webhook
  namespace: flux-system
spec:
  interval: 1h
  url: https://xunholy.github.io/fluxcd-kustomize-mutating-webhook