---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - cilium.yaml
  - cloudnative-pg.yaml
  - emberstack.yaml
  - external-dns.yaml
  - external-secrets.yaml
  - fluxcd-kustomize-mutating-webhook.yaml
  - jetstack.yaml
  - metrics-server.yaml
  - openebs.yaml
  - prometheus-community.yaml
  - tailscale.yaml