---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - external-dns.yaml
  - fluxcd-kustomize-mutating-webhook.yaml
  - prometheus-community.yaml
  - tailscale.yaml