---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-pihole
  namespace: network
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: 1.19.0
  install:
    remediation:
      retries: -1
  interval: 1h
  postRenderers:
    - kustomize:
        images:
          - name: registry.k8s.io/external-dns/external-dns
            newTag: v0.17.0
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: external-dns-pihole-values