---
domainFilters:
  - ${CLUSTER_DOMAIN}
env:
  - name: &name EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        key: *name
        name: external-dns-pihole
extraArgs:
  - --pihole-api-version=6
  - --pihole-server=http://192.168.0.53
policy: sync
provider: pihole
serviceMonitor:
  enabled: true
sources:
  - gateway-httproute
  - service
txtOwnerId: default
txtPrefix: k8s.