---
ingress:
  - hostname: ${CLUSTER_DOMAIN}
    service: &svc https://envoy-network-external-b1d9befd.network.svc.cluster.local:443
  - hostname: '*.${CLUSTER_DOMAIN}'
    service: *svc
  - service: http_status:404
originRequest:
  http2Origin: true
  originServerName: external.${CLUSTER_DOMAIN}