---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  interval: 1h
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      cloudflared:
        containers:
          app:
            args:
              - tunnel
              - run
            env:
              NO_AUTOUPDATE: true
              TUNNEL_LOGLEVEL: debug
              TUNNEL_METRICS: 0.0.0.0:8080
              TUNNEL_TRANSPORT_PROTOCOL: quic
            envFrom:
              - secretRef:
                  name: cloudflared-token
            image:
              repository: docker.io/cloudflare/cloudflared
              tag: 2025.6.0
            probes:
              liveness: &probe
                custom: true
                enabled: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /ready
                    port: 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness: *probe
        strategy: RollingUpdate
    persistence:
      config:
        name: cloudflared-config
        type: configMap
        globalMounts:
          - path: /etc/cloudflared/config.yaml
            readOnly: true
            subPath: config.yaml
    service:
      cloudflared:
        controller: cloudflared
        ports:
          http:
            port: 8080
    serviceMonitor:
      cloudflared:
        endpoints:
          - interval: 1m
            path: /metrics
            port: http
            scheme: http
            scrapeTimeout: 10s
        serviceName: cloudflared