---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: cloudflared-config
    namespace: network
    files:
      - config.yaml=./config.yaml
configurations:
  - kustomizeconfig.yaml
namespace: network
resources:
  - dnsendpoint.yaml
  - grafanadashboard.yaml
  - helmrelease.yaml