---
grafana:
  enabled: false
  forceDeployDashboards: true
  sidecar:
    dashboards:
      annotations:
        grafana_folder: kube-prometheus-stack
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
  route:
    main:
      enabled: true
      hostnames:
        - prometheus.themacdonald.house
      parentRefs:
        - name: internal
          namespace: envoy-gateway-system
          sectionName: https