---
grafana:
  enabled: false
  forceDeployDashboards: true
  sidecar:
    dashboards:
      annotations:
        grafana_folder: kube-prometheus-stack
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
  route:
    main:
      enabled: true
      hostnames:
        - 'prometheus.${CLUSTER_DOMAIN}'
      parentRefs:
        - name: internal
          namespace: network
          sectionName: https