---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../components/common
namespace: kube-system
resources:
  # - namespace.yaml
  - cilium/ks.yaml
  - metrics-server/ks.yaml