---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: themacdonald-house
spec:
  commonName: themacdonald.house
  dnsNames:
    - "themacdonald.house"
    - "*.themacdonald.house"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    rotationPolicy: Always
    size: 2048
  secretName: themacdonald-house-tls
  usages:
    - client auth
    - server auth