---
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
envoy:
  baseID: 100
  securityContext:
    capabilities:
      envoy:
        - BPF
        - NET_BIND_SERVICE
        - PERFMON
      keepCapNetBindService: true
gatewayAPI:
  enableAlpn: true
  enableAppProtocol: true
  enabled: true
  hostNetwork:
    enabled: true
ipam:
  mode: kubernetes
kubeProxyReplacement: false
nodePort:
  enabled: true
operator:
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
    trustCRDsExist: true
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - IPC_LOCK
      - KILL
      - NET_ADMIN
      - NET_RAW
      - SETGID
      - SETUID
      - SYS_ADMIN
      - SYS_RESOURCE
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE