---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../components/common
namespace: flux-system
resources:
  - gha-runner-scale-set/ks.yaml
  - gha-runner-scale-set-controller/ks.yaml