---
controller:
  enabled: true
  externalAttacher:
    enabled: false
  externalProvisioner:
    enabled: true
    extraArgs:
      - --capacity-ownerref-level=1
      - --enable-capacity=true
      - --leader-election=false
      - --node-deployment=true
      - --node-deployment-immediate-binding=false
  externalResizer:
    enabled: false
  externalSnapshotter:
    enabled: true
    extraArgs:
      - --leader-election=false
      - --node-deployment=true
  strategy: node
csiDriver:
  attachRequired: false
  fsGroupPolicy: File
  name: local-hostpath.cluster.local
  storageCapacity: true
driver:
  config:
    driver: local-hostpath
    local-hostpath:
      controllerBasePath: &storagePath /var/mnt/extra
      dirPermissionsGroup: 0
      dirPermissionsMode: "0770"
      dirPermissionsUser: 0
      shareBasePath: *storagePath
node:
  driver:
    extraVolumeMounts:
      - mountPath: *storagePath
        mountPropagation: Bidirectional
        name: local-hostpath
  extraVolumes:
    - hostpath:
        path: *storagePath
        type: DirectoryOrCreate
      name: local-hostpath
storageClasses:
  - allowVolumeExpansion: true
    defaultClass: true
    name: &name local-hostpath
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
volumeSnapshotClasses:
  - annotations:
      snapshot.storage.kubernetes.io/is-default-class: true
    deletionPolicy: Delete
    name: *name
    parameters: {}