---
controller:
  enabled: true
  externalAttacher:
    enabled: false
  externalProvisioner:
    enabled: true
  externalResizer:
    enabled: false
  externalSnapshotter:
    enabled: true
  strategy: node
csiDriver:
  fsGroupPolicy: File
  name: local-hostpath.cluster.local
  storageCapacity: true
driver:
  config:
    driver: local-hostpath
    local-hostpath:
      controllerBasePath: &storagePath /var/mnt/extra
      dirPermissionsGroup: 0
      dirPermissionsMode: "0770"
      dirPermissionsUser: 0
      shareBasePath: *storagePath
node:
  driver:
    extraVolumeMounts:
      - mountPath: *storagePath
        mountPropagation: Bidirectional
        name: local-hostpath
  extraVolumes:
    - hostpath:
        path: *storagePath
        type: DirectoryOrCreate
      name: local-hostpath
