---
instance:
  cluster:
    domain: "cluster.local"
    multitenant: false
    networkPolicy: false
  components:
    - helm-controller
    - kustomize-controller
    - notification-controller
    - source-controller
  distribution:
    version: 2.5.1
  kustomize:
    patches:
      # Add SOPS decryption to flux-system
      - patch: |
          apiVersion: v1
          kind: Kustomization
          metadata:
            name: flux-system
            namespace: flux-system
          spec:
            decryption:
              provider: sops
              secretRef:
                name: sops-age
        target:
          kind: Kustomization
          name: flux-system
  sync:
    kind: GitRepository
    path: kubernetes/clusters/home
    ref: "refs/heads/main"
    url: "https://github.com/iamryanmacdonald/homelab.git"