---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: cloudflared-values
    namespace: network
    files:
      - values.yaml=./values.yaml
configurations:
  - kustomizeconfig.yaml
resources:
  - dnsendpoint.yaml
  - helmrelease.yaml