---
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - disableDeletion: false
        editable: true
        folder: ''
        name: default
        options:
          path: /var/lib/grafana/dashboards/default
        orgId: 1
        type: file
      - disableDeletion: false
        editable: true
        folder: nginx
        name: nginx
        options:
          path: /var/lib/grafana/dashboards/nginx
        orgId: 1
        type: file
dashboards:
  default:
    cilium-dashboard:
      datasource: Prometheus
      url: https://raw.githubusercontent.com/cilium/cilium/refs/tags/v1.17.0/install/kubernetes/cilium/files/cilium-agent/dashboards/cilium-dashboard.json
    cilium-operator-dashboard:
      datasource: Prometheus
      url: https://raw.githubusercontent.com/cilium/cilium/refs/tags/v1.17.0/install/kubernetes/cilium/files/cilium-operator/dashboards/cilium-operator-dashboard.json
  nginx:
    nginx:
      url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/nginx.json
      datasource: Prometheus
    request-handling-performance:
      url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/grafana/dashboards/request-handling-performance.json
      datasource: Prometheus
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - access: proxy
        isDefault: true
        name: Prometheus
        type: prometheus
        url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090/
env:
  GF_SERVER_ROOT_URL: https://grafana.themacdonald.house
# ingress:
#   annotations:
#     external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
#   enabled: true
#   hosts:
#     - grafana.themacdonald.house
#   ingressClassName: internal
#   tls:
#     - hosts:
#         - grafana.themacdonald.house
#       secretName: themacdonald-house-production-tls
route:
  main:
    enabled: true
    hostnames:
      - grafana.themacdonald.house
    parentRefs:
      - name: internal
        namespace: kube-system
        sectionName: https
sidecar:
  dashboards:
    enabled: true
    folderAnnotation: grafana_folder
    provider:
      foldersFromFilesStructure: true