---
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - disableDeletion: false
        editable: true
        folder: ''
        name: default
        options:
          path: /var/lib/grafana/dashboards/default
        orgId: 1
        type: file
dashboards:
  default:
    cert-manager:
      datasource: Prometheus
      gnetId: 20842
      revision: 3
    cilium-dashboard:
      datasource: Prometheus
      url: https://raw.githubusercontent.com/cilium/cilium/refs/tags/v1.17.4/install/kubernetes/cilium/files/cilium-agent/dashboards/cilium-dashboard.json
    cilium-operator-dashboard:
      datasource: Prometheus
      url: https://raw.githubusercontent.com/cilium/cilium/refs/tags/v1.17.4/install/kubernetes/cilium/files/cilium-operator/dashboards/cilium-operator-dashboard.json
    cloudflared:
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
      gnetId: 17457
      revision: 6
    external-dns:
      datasource: Prometheus
      gnetId: 15038
      revision: 3
    hubble-dashboard:
      datasource: Prometheus
      url: https://raw.githubusercontent.com/cilium/cilium/refs/tags/v1.17.4/install/kubernetes/cilium/files/hubble/dashboards/hubble-dashboard.json   
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - access: proxy
        name: Alertmanager
        type: alertmanager
        uid: alertmanager
        url: http://kube-prometheus-stack-alertmanager.observability.svc.cluster.local:9093/
      - access: proxy
        isDefault: true
        name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090/
env:
  GF_DATE_FORMATS_USE_BROWSER_LOCALE: true
  GF_SERVER_ROOT_URL: https://grafana.themacdonald.house
route:
  main:
    enabled: true
    hostnames:
      - grafana.themacdonald.house
    parentRefs:
      - name: internal
        namespace: network
        sectionName: https
sidecar:
  dashboards:
    enabled: true
    folderAnnotation: grafana_folder
    provider:
      foldersFromFilesStructure: true
  datasources:
    enabled:  true