---
instance:
  cluster:
    domain: cluster.local
    multitenant: false
    networkPolicy: false
  components:
    - helm-controller
    - kustomize-controller
    - notification-controller
    - source-controller
  distribution:
    version: 2.5.1
  kustomize:
    patches:
      # Add SOPS decryption and post build substitution to flux-system
      - patch: |
          apiVersion: v1
          kind: Kustomization
          metadata:
            name: flux-system
            namespace: flux-system
          spec:
            decryption:
              provider: sops
              secretRef:
                name: sops-age
            postBuild:
              substituteFrom:
                - kind: ConfigMap
                  name: cluster-config
                - kind: Secret
                  name: cluster-secrets
        target:
          kind: Kustomization
          name: flux-system
  sync:
    interval: 1h
    kind: GitRepository
    name: flux-system
    path: kubernetes/clusters/oci
    ref: refs/heads/main
    url: https://github.com/iamryanmacdonald/gitops.git