---
instance:
  cluster:
    domain: cluster.local
    multitenant: false
    networkPolicy: false
  components:
    - helm-controller
    - kustomize-controller
    - notification-controller
    - source-controller
  distribution:
    version: 2.5.1
  sync:
    interval: 1h
    kind: GitRepository
    name: flux-system
    path: kubernetes/clusters/oci
    ref: refs/heads/main
    url: https://github.com/iamryanmacdonald/gitops.git