---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../components/common
namespace: security
resources:
  - cert-manager/ks.yaml
  - external-secrets/ks.yaml