---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
  - includeCRDs: true
    name: cilium
    namespace: kube-system
    releaseName: cilium
    repo: https://helm.cilium.io
    valuesFile: ../../../kubernetes/apps/base/kube-system/cilium/app/values.yaml
    version: 1.18.3
transformers:
  - transformers.yaml