---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
jobs:
  diff:
    if: ${{ needs.filter.outputs.changed-files != '[]' }}
    name: Flux Local - Diff
    needs: filter
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pull Request Branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: pull
          persist-credentials: false
      
      - name: Checkout Default Branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: default
          persist-credentials: false
          ref: ${{ github.event.repository.default_branch }}

      - name: Run flux-local diff
        uses: docker://ghcr.io/allenporter/flux-local:v7.5.4
        with:
          args: >-
            diff
            --all-namespaces
            --limit-bytes 10000
            --output-file diff.patch
            --path /github/workspace/pull/kubernetes/clusters/${{ matrix.cluster }}
            --path-orig /github/workspace/default/kubernetes/clusters/${{ matrix.cluster }}
            --sources "flux-system"
            --strip-attrs "chart,checksum/config,helm.sh/chart,kubernetes.io/version"
            --unified 6
      
      - id: diff
        name: Generate Diff
        run: |
          echo 'diff <<EOF' >> $GITHUB_OUTPUT
          cat diff.patch >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      
      - id: app-token
        if: ${{ steps.diff.outputs.diff != '' }}
        name: Generate Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      
      - continue-on-error: true
        if: ${{ steps.diff.outputs.diff != '' }}
        name: Add Comment
        uses: marocchino/sticky-pull-request-comment@67d0dec7b07ed060a405f9b2a64b8ab319fdd7db # v2.9.2
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          header: ${{ github.event.pull_request.number }}/kubernetes/${{ matrix.resource }}
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
    strategy:
      fail-fast: false
      matrix:
        cluster:
          - oci
        resource:
          - helmrelease
          - kustomization
  filter:
    name: Flux Local - Filter
    outputs:
      changed-files: ${{ steps.changed-files.outputs.changed_files }}
    runs-on: ubuntu-latest
    steps:
      - id: changed-files
        name: Get changed files
        uses: bjw-s-labs/action-changed-files@930cef8463348e168cab7235c47fe95a7a235f65 # v0.3.3
        with:
          patterns: kubernetes/**/*
  success:
    if: ${{ !cancelled() }}
    name: Flux Local - Success
    needs:
      - diff
      - test
    runs-on: ubuntu-latest
    steps:
      - if: ${{ contains(needs.*.result, 'failure') }}
        name: Any jobs failed?
        run: exit 1
      
      - if: ${{ contains(needs.*.result, 'failure') }}
        name: All jobs passed or skipped?
        run: echo "All jobs passed or skipped" && echo "${{ toJSON(needs.*.result) }}"
  test:
    if: ${{ needs.filter.outputs.changed-files != '[]' }}
    name: Flux Local - Test
    needs: filter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Run flux-local test
        uses: docker://ghcr.io/allenporter/flux-local:v7.5.4
        with:
          args: >-
            test
            --all-namespaces
            --enable-helm
            --path /github/workspace/kubernetes/clusters/${{ matrix.cluster }}
            --verbose
    strategy:
      matrix:
        cluster:
          - oci
name: Flux Local
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: read