---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
jobs:
  changed-files:
    name: Terraform - Changed Files
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - id: changed-files
        name: Get changed files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47.0.0
        with:
          dir_names: true
          dir_names_max_depth: 2
          files: terraform/**
          files_ignore: terraform/_modules/**
          matrix: true

      - name: List changed files
        run: echo ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
  apply:
    environment: terraform
    name: Terraform - Apply
    needs:
      - changed-files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Terraform - Install
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_wrapper: false

      - env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_ENDPOINT_URL_S3: ${{ vars.AWS_ENDPOINT_URL_S3 }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        name: Terraform - init
        run: |
          terraform init \
            -no-color
        working-directory: ${{ matrix.paths }}

      - env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_ENDPOINT_URL_S3: ${{ vars.AWS_ENDPOINT_URL_S3 }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_bitwarden_access_token: ${{ secrets.BITWARDEN_ACCESS_TOKEN }}
          TF_VAR_bitwarden_organization_id: ${{ vars.BITWARDEN_ORGANIZATION_ID }}
        name: Terraform - apply
        run: |
          terraform apply \
            -input=false \
            -no-color \
            -var "cicd=true"
        working-directory: ${{ matrix.paths }}
    strategy:
      fail-fast: false
      matrix:
        paths: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 4
name: Terraform - Apply
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/terraform-apply.yaml
      - terraform/**
  workflow_dispatch:
